### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by sycured** [ThatNerdUKnow/libvmaf-sys#1]
I'm trying to move from [vmaf-sys](https://github.com/colbyn/vmaf-sys) to libvmaf-sys but due to missing example code, the migration is really hard.
Also about moving to the new API because compute_vmaf is deprecated.
Do you have any example code that can help?
Thanks

**Comment by ThatNerdUKnow** [comment]
I'm currently in the process of writing an ergonomic wrapper library [libvmaf-rs](https://github.com/ThatNerdUKnow/libvmaf-rs)
However, if you were so inclined, you could use this library directly
This library is pretty much just a build/bindgen script, so any examples from the original C libvmaf repository should also apply

**Comment by ThatNerdUKnow** [comment]
Development of libvmaf-rs is currently paused until the following PR is merged
https://github.com/Netflix/vmaf/pull/1129

**Comment by sycured** [comment]
Thank you but I can't access libvmaf-rs

![Screenshot_2022-12-11-14-14-06-288_com.github.android.jpg](https://user-images.githubusercontent.com/60801403/206923966-8e338975-0f9b-4b43-809c-1270e1419934.jpg)

**Comment by ThatNerdUKnow** [comment]
Oh, sorry about that. I forgot that it's set to private. I'll fix that

**Comment by ThatNerdUKnow** [comment]
Repo is public now
Keep in mind that libvmaf-rs is still in development and is not currently available on crates.io

**Comment by ThatNerdUKnow** [comment]
I could use help in issue https://github.com/ThatNerdUKnow/libvmaf-rs/issues/2
I'm thinking that I could turn a path into a ffmpegformat and then decode them into an iterator of AVFrames then somehow translate each AVFrame into a VmafPicture by copying over the YUV data into VmafPicture->data[0]
